---

classes:
  - 'profiles::rabbitmq'
  - 'profiles::digitalregister_app'

rabbitmq_users:
  rabbitmqadmin:
    admin: true
    password: 'rabbitmqadminrabbitmqadmin'

rabbitmq_user_permissions:
  rabbitmqadmin@/:
    configure_permission: '.*'
    read_permission: '.*'
    write_permission: '.*'

# gues user is currently requied for the feeder app - issue raised with dev team
profiles::rabbitmq::delete_guest_user: false
